require:
  - rubocop-minitest

AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 20
  CountAsOne: ['array', 'hash', 'heredoc']

Layout/LineLength:
  Max: 100

Style/EndOfLine:
  EnforcedStyle: lf

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

# TODO: add documentation
Style/Documentation:
  Enabled: false

# TODO:
Gemspec/RequireMFA:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
